@extends('layouts.skydash-v')
@section('title', 'Assistance Release')
@section('heading', 'Local E-CLIP Committee')

@push('styles')
<style>
    .release-hero{background:linear-gradient(125deg,#173b74,#2f6fed);border-radius:16px;box-shadow:0 10px 28px rgba(47,111,237,.16);color:#fff;overflow:hidden;padding:1.5rem;position:relative}.release-hero::after{background:rgba(255,255,255,.08);border-radius:50%;content:'';height:180px;position:absolute;right:-45px;top:-90px;width:180px}.release-hero h2{color:#fff;font-size:1.55rem;font-weight:700}.release-hero p{font-size:.82rem;opacity:.85}.release-count{background:rgba(255,255,255,.18);border:1px solid rgba(255,255,255,.28);border-radius:12px;min-width:100px;padding:.7rem 1rem;position:relative;text-align:center;z-index:1}.release-count strong{display:block;font-size:1.35rem;line-height:1.1}.release-count small{font-size:.67rem;text-transform:uppercase}
    .queue-card{border:1px solid #e7ecf3;border-radius:14px;box-shadow:0 4px 16px rgba(23,43,77,.045);overflow:hidden}.queue-card .card-body{padding:0}.queue-table{margin:0}.queue-table thead th{background:#f7f9fc;border:0;color:#718096;font-size:.7rem;font-weight:700;letter-spacing:.04em;padding:.9rem 1rem;text-transform:uppercase;white-space:nowrap}.queue-table tbody td{border-color:#edf1f6;color:#52616f;font-size:.82rem;padding:.9rem 1rem;vertical-align:middle}.case-link{color:#244a83;font-weight:700}.beneficiary-detail{align-items:center;display:inline-flex}.beneficiary-detail i{margin-right:.4rem}.money-column{text-align:right}.money{align-items:baseline;color:#173b74;display:inline-flex;font-variant-numeric:tabular-nums;font-weight:700;justify-content:flex-end;white-space:nowrap}.status-badge{background:#eaf1ff;border-radius:14px;color:#2f6fed;display:inline-flex;font-size:.68rem;font-weight:700;padding:.32rem .65rem}.release-progress{background:#edf2f7;border-radius:5px;height:5px;margin-left:auto;margin-top:.4rem;min-width:100px;overflow:hidden;width:100px}.release-progress span{background:#20a779;display:block;height:100%}.open-btn{align-items:center;border-radius:8px;display:inline-flex;font-weight:600}.open-btn i{margin-left:.35rem}.queue-pagination{border-top:1px solid #edf1f6;padding:1rem 1.25rem}.empty-queue{color:#8492a6;padding:3rem 1rem;text-align:center}.empty-queue i{color:#bcc7d6;display:block;font-size:2.3rem;margin-bottom:.55rem}
    @media(max-width:767px){.release-hero{padding:1.2rem}.release-hero h2{font-size:1.3rem}.release-count{margin-top:1rem;text-align:left}.queue-table thead{display:none}.queue-table,.queue-table tbody,.queue-table tr,.queue-table td{display:block;width:100%}.queue-table tr{border-bottom:1px solid #e7ecf3;padding:.65rem 0}.queue-table tbody td{border:0;padding:.35rem 1rem}.money-column{text-align:left}.release-progress{margin-left:0}.queue-table td:last-child{text-align:left!important}}
</style>
@endpush

@section('content')
<div class="release-hero mb-4"><div class="d-flex flex-column flex-md-row align-items-md-center justify-content-between position-relative" style="z-index:1"><div><h2 class="mb-1">Assistance Release Queue</h2><p class="mb-0"><i class="mdi mdi-map-marker-outline mr-1"></i>Transferred cases are limited to your assigned municipality.</p></div><div class="release-count"><strong>{{ number_format($cases->total()) }}</strong><small>Total cases</small></div></div></div>
<section class="card queue-card" aria-label="Assistance release cases"><div class="card-body"><div class="table-responsive"><table class="table queue-table"><thead><tr><th>Case Number</th><th>Beneficiary ID</th><th class="money-column">Transferred</th><th class="money-column">Released</th><th>Status</th><th class="text-right">Action</th></tr></thead><tbody>
@forelse($cases as $case)
    @php
        $transferred = (float) $case->fundTransactions->where('type', 'transfer')->sum('amount');
        $released = (float) $case->assistanceReleases->sum('amount');
        $percentage = $transferred > 0 ? min(100, ($released / $transferred) * 100) : 0;
    @endphp
    <tr><td><a class="case-link" href="{{ route('local_eclip.cases.show',$case) }}">{{ $case->case_number }}</a></td><td><span class="beneficiary-detail"><i class="mdi mdi-account-key-outline text-muted"></i>{{ $case->formerRebel->classified_id }}</span></td><td class="money-column"><span class="money">₱{{ number_format($transferred,2) }}</span></td><td class="money-column"><span class="money">₱{{ number_format($released,2) }}</span><div class="release-progress" title="{{ number_format($percentage,1) }}% released"><span style="width:{{ $percentage }}%"></span></div></td><td><span class="status-badge">{{ $case->status->label() }}</span></td><td class="text-right"><a href="{{ route('local_eclip.cases.show',$case) }}" class="btn btn-sm btn-outline-primary open-btn">Open Release <i class="mdi mdi-arrow-right"></i></a></td></tr>
@empty<tr><td colspan="6"><div class="empty-queue"><i class="mdi mdi-cash-multiple"></i><strong class="d-block text-dark mb-1">Release queue is clear</strong><span>No transferred cases are currently available.</span></div></td></tr>@endforelse
</tbody></table></div></div>@if($cases->hasPages())<div class="queue-pagination">{{ $cases->links() }}</div>@endif</section>
@endsection
