@extends('layouts.skydash-v')
@section('title', 'E-CLIP Funding')
@section('heading', 'Fund Allocation and Transfer')

@push('styles')
<style>
    .funding-page{--primary:#2f6fed;--navy:#172b4d;--border:#e7ecf3}.funding-back{align-items:center;color:#64748b;display:inline-flex;font-size:.82rem;font-weight:600;gap:.4rem;margin-bottom:1rem}.funding-back:hover{color:#2f6fed;text-decoration:none}.case-hero{background:linear-gradient(125deg,#173b74,#2f6fed);border-radius:16px;box-shadow:0 10px 28px rgba(47,111,237,.16);color:#fff;overflow:hidden;padding:1.5rem;position:relative}.case-hero::after{background:rgba(255,255,255,.08);border-radius:50%;content:'';height:180px;position:absolute;right:-45px;top:-90px;width:180px}.case-eyebrow{font-size:.7rem;font-weight:700;letter-spacing:.1em;opacity:.75;text-transform:uppercase}.case-hero h2{color:#fff;font-size:1.55rem;font-weight:700}.case-meta{display:flex;flex-wrap:wrap;gap:.7rem 1.5rem}.case-meta span{align-items:center;display:inline-flex;font-size:.82rem;gap:.4rem;opacity:.9}.case-status{background:rgba(255,255,255,.18);border:1px solid rgba(255,255,255,.3);border-radius:18px;font-size:.7rem;font-weight:700;padding:.4rem .75rem;position:relative;z-index:1}
    .money-card,.funding-card{border:1px solid var(--border);border-radius:14px;box-shadow:0 4px 16px rgba(23,43,77,.045)}.money-card{overflow:hidden;position:relative}.money-card::before{background:var(--money-color);content:'';height:4px;left:0;position:absolute;right:0;top:0}.money-card .card-body{align-items:center;display:flex;gap:.85rem;padding:1.15rem}.money-icon{align-items:center;background:var(--money-bg);border-radius:10px;color:var(--money-color);display:flex;flex:0 0 42px;font-size:1.2rem;height:42px;justify-content:center}.money-card small{color:#718096;display:block;font-size:.68rem;font-weight:700;text-transform:uppercase}.money-card strong{color:var(--navy);display:block;font-size:1.2rem;margin-top:.15rem}.money-approved{--money-bg:#f2ebff;--money-color:#805ad5}.money-allocated{--money-bg:#eaf1ff;--money-color:#2f6fed}.money-transferred{--money-bg:#e8f8f1;--money-color:#20a779}.funding-progress{background:#edf2f7;border-radius:7px;height:8px;overflow:hidden}.funding-progress span{background:linear-gradient(90deg,#2f6fed,#20a779);display:block;height:100%}
    .funding-card .card-body{padding:1.4rem}.section-icon{align-items:center;background:#eaf1ff;border-radius:10px;color:#2f6fed;display:flex;flex:0 0 40px;font-size:1.15rem;height:40px;justify-content:center;width:40px}.section-title{color:var(--navy);font-size:1rem;font-weight:700;margin:0 0 .2rem}.section-subtitle{color:#8492a6;font-size:.76rem;margin:0}.next-step{align-items:flex-start;background:#eef5ff;border:1px solid #ccddfb;border-radius:10px;color:#36537c;display:flex;font-size:.76rem;gap:.55rem;padding:.75rem .85rem}.next-step i{color:#2f6fed;font-size:1rem}.field-label{color:#42526b;font-size:.77rem;font-weight:600}.optional{color:#94a3b8;font-size:.68rem;font-weight:400}.form-control{border-color:#dfe5ee;border-radius:8px}.form-control:focus{border-color:#80a6ee;box-shadow:0 0 0 3px rgba(47,111,237,.1)}.currency-field{position:relative}.currency-field::before{color:#64748b;content:'₱';left:.85rem;position:absolute;top:2.42rem;z-index:2}.currency-field input{padding-left:1.8rem}
    .proof-upload{background:#f8fafc;border:1px dashed #aebbd0;border-radius:11px;padding:.9rem;transition:.2s}.proof-upload:focus-within{background:#f2f6ff;border-color:#2f6fed;box-shadow:0 0 0 3px rgba(47,111,237,.1)}.proof-picker{align-items:center;cursor:pointer;display:flex;gap:.7rem;margin:0}.proof-icon{align-items:center;background:#eaf1ff;border-radius:9px;color:#2f6fed;display:flex;flex:0 0 40px;font-size:1.1rem;height:40px;justify-content:center}.proof-title{color:#334155;display:block;font-size:.8rem;font-weight:600}.proof-help,.proof-name{color:#8492a6;display:block;font-size:.69rem}.proof-name{color:#64748b;margin-top:.15rem;overflow-wrap:anywhere}.proof-upload input[type=file]{border:0;clip:rect(0,0,0,0);height:1px;overflow:hidden;padding:0;position:absolute;white-space:nowrap;width:1px}.record-button{border-radius:9px;font-weight:600;padding:.65rem 1rem}.security-note{align-items:flex-start;background:#f7f9fc;border-radius:9px;color:#718096;display:flex;font-size:.71rem;gap:.5rem;padding:.7rem .8rem}
    .history-table{margin:0}.history-table thead th{background:#f7f9fc;border:0;color:#718096;font-size:.69rem;font-weight:700;letter-spacing:.04em;padding:.8rem;text-transform:uppercase;white-space:nowrap}.history-table tbody td{border-color:#edf1f6;color:#52616f;font-size:.78rem;padding:.8rem;vertical-align:middle}.type-badge{border-radius:12px;display:inline-flex;font-size:.66rem;font-weight:700;padding:.28rem .55rem}.type-allocation{background:#eaf1ff;color:#2f6fed}.type-transfer{background:#e8f8f1;color:#16845e}.reference{color:#244a83;font-weight:700}.amount{color:#173b74;font-weight:700}.proof-link{align-items:center;background:#eef4ff;border-radius:8px;color:#2f6fed;display:inline-flex;font-size:.72rem;font-weight:600;gap:.35rem;padding:.4rem .6rem}.proof-link:hover{background:#dfeaff;color:#1f55bd;text-decoration:none}.empty-state{color:#8492a6;padding:2.5rem 1rem;text-align:center}.empty-state i{display:block;font-size:2rem;margin-bottom:.4rem}
    @media(max-width:767px){.case-hero{padding:1.2rem}.case-hero h2{font-size:1.3rem}.case-status{margin-top:.8rem}.funding-card .card-body{padding:1.1rem}.proof-upload .btn{margin-top:.8rem;width:100%}.history-table thead{display:none}.history-table,.history-table tbody,.history-table tr,.history-table td{display:block;width:100%}.history-table tr{border-bottom:1px solid #e7ecf3;padding:.65rem 0}.history-table tbody td{border:0;padding:.3rem 1rem}}
</style>
@endpush

@section('content')
@php
    $approvedReview = $case->dilgReviews->where('decision', 'approved')->sortByDesc('reviewed_at')->first();
    $approvedAmount = (float) ($approvedReview?->revision?->assessed_amount ?? 0);
    $allocated = (float) $case->fundTransactions->where('type', 'allocation')->sum('amount');
    $transferred = (float) $case->fundTransactions->where('type', 'transfer')->sum('amount');
    $isAllocation = in_array($case->status, [\App\Enums\EclipCaseStatus::Approved, \App\Enums\EclipCaseStatus::FundAllocationPending], true);
    $isTransfer = $case->status === \App\Enums\EclipCaseStatus::FundsAllocated;
    $transactionType = $isAllocation ? 'allocation' : ($isTransfer ? 'transfer' : null);
    $availableAmount = $isAllocation ? max(0, $approvedAmount - $allocated) : ($isTransfer ? max(0, $allocated - $transferred) : 0);
    $allocationPercentage = $approvedAmount > 0 ? min(100, ($allocated / $approvedAmount) * 100) : 0;
    $transferPercentage = $allocated > 0 ? min(100, ($transferred / $allocated) * 100) : 0;
@endphp
<div class="funding-page">
    <a href="{{ route('eclip_funding.cases.index') }}" class="funding-back"><i class="mdi mdi-arrow-left"></i> Back to funding queue</a>
    <section class="case-hero mb-4" aria-labelledby="funding-case-number"><div class="d-flex flex-column flex-md-row justify-content-between align-items-md-start position-relative" style="z-index:1"><div><div class="case-eyebrow mb-1">Fund Allocation and Transfer</div><h2 id="funding-case-number" class="mb-3">{{ $case->case_number }}</h2><div class="case-meta"><span><i class="mdi mdi-account-key-outline"></i>{{ $case->formerRebel->classified_id }}</span><span><i class="mdi mdi-map-marker-outline"></i>{{ $case->formerRebel->municipality?->name ?? 'Not assigned' }}</span>@if($approvedReview?->revision?->category)<span><i class="mdi mdi-tag-outline"></i>{{ $approvedReview->revision->category->name }}</span>@endif</div></div><span class="case-status"><i class="mdi mdi-progress-check mr-1"></i>{{ $case->status->label() }}</span></div></section>

    <div class="row"><div class="col-md-4 mb-3"><div class="card money-card money-approved h-100"><div class="card-body"><div class="money-icon"><i class="mdi mdi-shield-check-outline"></i></div><div><small>Approved</small><strong>₱{{ number_format($approvedAmount,2) }}</strong></div></div></div></div><div class="col-md-4 mb-3"><div class="card money-card money-allocated h-100"><div class="card-body"><div class="money-icon"><i class="mdi mdi-bank-outline"></i></div><div><small>Allocated</small><strong>₱{{ number_format($allocated,2) }}</strong></div></div></div></div><div class="col-md-4 mb-3"><div class="card money-card money-transferred h-100"><div class="card-body"><div class="money-icon"><i class="mdi mdi-bank-transfer-out"></i></div><div><small>Transferred</small><strong>₱{{ number_format($transferred,2) }}</strong></div></div></div></div></div>
    <div class="row mb-4"><div class="col-md-6 mb-2 mb-md-0"><div class="d-flex justify-content-between text-muted small mb-1"><span>Allocation progress</span><span>{{ number_format($allocationPercentage,1) }}%</span></div><div class="funding-progress"><span style="width:{{ $allocationPercentage }}%"></span></div></div><div class="col-md-6"><div class="d-flex justify-content-between text-muted small mb-1"><span>Transfer progress</span><span>{{ number_format($transferPercentage,1) }}%</span></div><div class="funding-progress"><span style="width:{{ $transferPercentage }}%"></span></div></div></div>

    <div class="row"><div class="col-xl-7">
        @can('manageFunding',$case)
            @if($transactionType)
                <section class="card funding-card mb-4" aria-labelledby="transaction-title"><div class="card-body">
                    <div class="d-flex align-items-center mb-3"><div class="section-icon mr-3"><i class="mdi {{ $isAllocation ? 'mdi-bank-plus' : 'mdi-bank-transfer-out' }}"></i></div><div><h3 id="transaction-title" class="section-title">Record {{ str($transactionType)->title() }}</h3><p class="section-subtitle">Add the next authorized funding transaction to the immutable ledger.</p></div></div>
                    <div class="next-step mb-4"><i class="mdi mdi-information-outline"></i><span>{{ $isAllocation ? 'Allocate funds up to the approved assistance amount.' : 'Transfer allocated funds to the Local E-CLIP Committee. A proof document is required.' }} Available balance: <strong>₱{{ number_format($availableAmount,2) }}</strong>.</span></div>
                    <form method="POST" action="{{ route('eclip_funding.transactions.store',$case) }}" enctype="multipart/form-data" data-funding-form>@csrf
                        <input type="hidden" name="type" value="{{ $transactionType }}">
                        <div class="row"><div class="form-group col-md-4 currency-field"><label for="amount" class="field-label">{{ str($transactionType)->title() }} Amount</label><input id="amount" type="number" name="amount" value="{{ old('amount') }}" min="0.01" max="{{ number_format($availableAmount,2,'.','') }}" step="0.01" class="form-control @error('amount') is-invalid @enderror" required>@error('amount')<div class="invalid-feedback">{{ $message }}</div>@enderror<small class="text-muted">Maximum ₱{{ number_format($availableAmount,2) }}</small></div><div class="form-group col-md-4"><label for="reference_number" class="field-label">Reference Number</label><input id="reference_number" name="reference_number" value="{{ old('reference_number') }}" maxlength="150" class="form-control @error('reference_number') is-invalid @enderror" placeholder="Official reference number" required>@error('reference_number')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="form-group col-md-4"><label for="transaction_date" class="field-label">Transaction Date</label><input id="transaction_date" type="date" name="transaction_date" value="{{ old('transaction_date') }}" max="{{ now()->toDateString() }}" class="form-control @error('transaction_date') is-invalid @enderror" required>@error('transaction_date')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
                        <div class="form-group"><label for="remarks" class="field-label">Remarks <span class="optional">(optional)</span></label><textarea id="remarks" name="remarks" rows="3" maxlength="5000" class="form-control @error('remarks') is-invalid @enderror" placeholder="Add transaction notes...">{{ old('remarks') }}</textarea>@error('remarks')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                        <div class="form-group"><label class="field-label">Proof Document <span class="optional">({{ $isTransfer ? 'required for transfers' : 'optional for allocations' }})</span></label><div class="proof-upload"><input id="proof" type="file" name="proof" accept=".pdf,.jpg,.jpeg,.png" @required($isTransfer) data-file-input><div class="d-flex flex-column flex-md-row align-items-md-center justify-content-between"><label for="proof" class="proof-picker"><span class="proof-icon"><i class="mdi mdi-cloud-upload-outline"></i></span><span><span class="proof-title">Choose transaction proof</span><span class="proof-help">PDF, JPG, or PNG · Maximum 10 MB</span><span class="proof-name" data-file-name>No file selected</span></span></label><button class="btn btn-primary record-button" data-submit-button><i class="mdi mdi-content-save-check-outline mr-1"></i>Record {{ str($transactionType)->title() }}</button></div></div>@error('proof')<div class="text-danger small mt-2" role="alert">{{ $message }}</div>@enderror</div>
                        @error('type')<div class="alert alert-danger py-2" role="alert">{{ $message }}</div>@enderror
                    </form><div class="security-note"><i class="mdi mdi-shield-lock-outline"></i><span>Funding proofs are stored privately. Transactions cannot be edited after recording.</span></div>
                </div></section>
            @endif
        @endcan
    </div><div class="col-xl-5"><section class="card funding-card mb-4" aria-labelledby="history-title"><div class="card-body"><div class="d-flex align-items-center mb-4"><div class="section-icon mr-3"><i class="mdi mdi-history"></i></div><div><h3 id="history-title" class="section-title">Immutable Transaction History</h3><p class="section-subtitle">Official allocation and transfer ledger.</p></div></div><div class="table-responsive"><table class="table history-table"><thead><tr><th>Type</th><th>Reference</th><th>Amount</th><th>Date</th><th>Recorded By</th><th>Proof</th></tr></thead><tbody>@forelse($case->fundTransactions->sortByDesc('created_at') as $transaction)<tr><td><span class="type-badge type-{{ $transaction->type }}">{{ str($transaction->type)->title() }}</span></td><td><span class="reference">{{ $transaction->reference_number }}</span></td><td><span class="amount">₱{{ number_format((float)$transaction->amount,2) }}</span></td><td>{{ $transaction->transaction_date->format('M d, Y') }}</td><td>{{ $transaction->creator->name }}</td><td>@if($transaction->proof_path)<a class="proof-link" target="_blank" rel="noopener" href="{{ route('eclip_funding.transactions.proof',$transaction) }}"><i class="mdi mdi-file-eye-outline"></i>View</a>@else<span class="text-muted">—</span>@endif</td></tr>@empty<tr><td colspan="6"><div class="empty-state"><i class="mdi mdi-bank-clock"></i>No funding transactions have been recorded.</div></td></tr>@endforelse</tbody></table></div></div></section></div></div>
</div>
@endsection

@push('scripts')
<script>
var fundingForm=document.querySelector('[data-funding-form]');if(fundingForm){var input=fundingForm.querySelector('[data-file-input]');var name=fundingForm.querySelector('[data-file-name]');var button=fundingForm.querySelector('[data-submit-button]');input.addEventListener('change',function(){name.textContent=input.files.length?input.files[0].name:'No file selected';});fundingForm.addEventListener('submit',function(){button.disabled=true;button.innerHTML='<i class="mdi mdi-loading mdi-spin mr-1"></i>Recording...';});}
</script>
@endpush
