@extends('layouts.skydash-v')
@section('title', 'Assistance Assessment')
@section('heading', 'E-CLIP Assistance Assessment')

@push('styles')
<style>
    .assessment-hero { background: linear-gradient(125deg,#173b74,#2f6fed); border-radius:16px; box-shadow:0 10px 28px rgba(47,111,237,.16); color:#fff; padding:1.5rem; overflow:hidden; position:relative }.assessment-hero::after{background:rgba(255,255,255,.08);border-radius:50%;content:'';height:180px;position:absolute;right:-45px;top:-90px;width:180px}.assessment-hero h2{color:#fff;font-size:1.55rem;font-weight:700}.assessment-hero p{font-size:.82rem;opacity:.85}.assessment-count{background:rgba(255,255,255,.18);border:1px solid rgba(255,255,255,.28);border-radius:12px;min-width:100px;padding:.7rem 1rem;position:relative;text-align:center;z-index:1}.assessment-count strong{display:block;font-size:1.35rem;line-height:1.1}.assessment-count small{font-size:.67rem;text-transform:uppercase}
    .assessment-card{border:1px solid #e7ecf3;border-radius:14px;box-shadow:0 4px 16px rgba(23,43,77,.045);overflow:hidden}.assessment-card .card-body{padding:0}.assessment-table{margin:0}.assessment-table thead th{background:#f7f9fc;border:0;color:#718096;font-size:.7rem;font-weight:700;letter-spacing:.04em;padding:.9rem 1rem;text-transform:uppercase;white-space:nowrap}.assessment-table tbody td{border-color:#edf1f6;color:#52616f;font-size:.82rem;padding:.9rem 1rem;vertical-align:middle}.case-link{color:#244a83;font-weight:700}.beneficiary-detail{align-items:center;display:inline-flex}.beneficiary-detail i{margin-right:.4rem}.status-badge{background:#eaf1ff;border-radius:14px;color:#2f6fed;display:inline-flex;font-size:.68rem;font-weight:700;padding:.32rem .65rem}.amount-column{text-align:right}.amount{color:#173b74;font-variant-numeric:tabular-nums;font-weight:700;white-space:nowrap}.open-btn{align-items:center;border-radius:8px;display:inline-flex;font-weight:600}.open-btn i{margin-left:.35rem}.assessment-pagination{border-top:1px solid #edf1f6;padding:1rem 1.25rem}.empty-queue{color:#8492a6;padding:3rem 1rem;text-align:center}.empty-queue i{color:#bcc7d6;display:block;font-size:2.3rem;margin-bottom:.55rem}
    @media(max-width:767px){.assessment-hero{padding:1.2rem}.assessment-hero h2{font-size:1.3rem}.assessment-count{margin-top:1rem;text-align:left}.assessment-table thead{display:none}.assessment-table,.assessment-table tbody,.assessment-table tr,.assessment-table td{display:block;width:100%}.assessment-table tr{border-bottom:1px solid #e7ecf3;padding:.65rem 0}.assessment-table tbody td{border:0;padding:.35rem 1rem}.amount-column{text-align:left}.assessment-table td:last-child{text-align:left!important}.open-btn{justify-content:center;width:100%}}
</style>
@endpush

@section('content')
<div class="assessment-hero mb-4"><div class="d-flex flex-column flex-md-row align-items-md-center justify-content-between position-relative" style="z-index:1"><div><h2 class="mb-1">Assessment Queue</h2><p class="mb-0"><i class="mdi mdi-map-marker-outline mr-1"></i>Cases are limited to your assigned municipality.</p></div><div class="assessment-count"><strong>{{ number_format($cases->total()) }}</strong><small>Total cases</small></div></div></div>
<section class="card assessment-card" aria-label="Assistance assessment cases"><div class="card-body"><div class="table-responsive"><table class="table assessment-table"><thead><tr><th>Case Number</th><th>Beneficiary ID</th><th>Status</th><th class="amount-column">Latest Assessed Amount</th><th class="text-right">Action</th></tr></thead><tbody>
@forelse($cases as $case)
    <tr><td><a class="case-link" href="{{ route('eclip_assessor.cases.show', $case) }}">{{ $case->case_number }}</a></td><td><span class="beneficiary-detail"><i class="mdi mdi-account-key-outline text-muted"></i>{{ $case->formerRebel->classified_id }}</span></td><td><span class="status-badge">{{ $case->status->label() }}</span></td><td class="amount-column"><span class="amount">{{ $case->assistanceRequest?->latestRevision?->assessed_amount !== null ? '₱'.number_format((float) $case->assistanceRequest->latestRevision->assessed_amount, 2) : 'Pending' }}</span></td><td class="text-right"><a href="{{ route('eclip_assessor.cases.show', $case) }}" class="btn btn-sm btn-outline-primary open-btn">Open Assessment <i class="mdi mdi-arrow-right"></i></a></td></tr>
@empty<tr><td colspan="5"><div class="empty-queue"><i class="mdi mdi-clipboard-text-outline"></i><strong class="d-block text-dark mb-1">Assessment queue is clear</strong><span>No cases are currently available for assistance assessment.</span></div></td></tr>@endforelse
</tbody></table></div></div>@if($cases->hasPages())<div class="assessment-pagination">{{ $cases->links() }}</div>@endif</section>
@endsection
