@extends('layouts.skydash-v')
@section('title', 'Assistance Assessment')
@section('heading', 'E-CLIP Assistance Assessment')

@push('styles')
<style>
    .assessment-page{--primary:#2f6fed;--navy:#172b4d;--border:#e7ecf3}.assessment-back{align-items:center;color:#64748b;display:inline-flex;font-size:.82rem;font-weight:600;gap:.4rem;margin-bottom:1rem}.assessment-back:hover{color:#2f6fed;text-decoration:none}.case-hero{background:linear-gradient(125deg,#173b74,#2f6fed);border-radius:16px;box-shadow:0 10px 28px rgba(47,111,237,.16);color:#fff;overflow:hidden;padding:1.5rem;position:relative}.case-hero::after{background:rgba(255,255,255,.08);border-radius:50%;content:'';height:180px;position:absolute;right:-45px;top:-90px;width:180px}.case-eyebrow{font-size:.7rem;font-weight:700;letter-spacing:.1em;opacity:.75;text-transform:uppercase}.case-hero h2{color:#fff;font-size:1.55rem;font-weight:700}.case-meta{display:flex;flex-wrap:wrap;gap:.7rem 1.5rem}.case-meta span{align-items:center;display:inline-flex;font-size:.82rem;gap:.4rem;opacity:.9}.case-status{background:rgba(255,255,255,.18);border:1px solid rgba(255,255,255,.3);border-radius:18px;font-size:.7rem;font-weight:700;padding:.4rem .75rem;position:relative;z-index:1}
    .assessment-card{border:1px solid var(--border);border-radius:14px;box-shadow:0 4px 16px rgba(23,43,77,.045)}.assessment-card .card-body{padding:1.4rem}.section-icon{align-items:center;background:#eaf1ff;border-radius:10px;color:#2f6fed;display:flex;flex:0 0 40px;font-size:1.15rem;height:40px;justify-content:center;margin-right:1.1rem!important;width:40px}.section-title{color:var(--navy);font-size:1rem;font-weight:700;margin:0 0 .2rem}.section-subtitle{color:#8492a6;font-size:.76rem;line-height:1.4;margin:0}.field-label{color:#42526b;font-size:.77rem;font-weight:600}.optional{color:#94a3b8;font-size:.68rem;font-weight:400}.form-control{border-color:#dfe5ee;border-radius:8px}.form-control:focus{border-color:#80a6ee;box-shadow:0 0 0 3px rgba(47,111,237,.1)}.currency-input{position:relative}.currency-symbol{align-items:center;color:#64748b;display:flex;height:100%;justify-content:center;left:0;pointer-events:none;position:absolute;top:0;width:2rem;z-index:2}.currency-input input{padding-left:2rem}.save-button,.submit-button{align-items:center;border-radius:9px;display:inline-flex;font-weight:600;padding:.65rem 1rem}.save-button i,.submit-button i{margin-right:.35rem}
    .submission-panel{background:linear-gradient(125deg,#eefaf5,#f7fcfa);border:1px solid #ccebdc;border-radius:12px;padding:1rem}.submission-panel strong{color:#176b50;display:block;font-size:.85rem}.submission-panel span{color:#5f7f73;font-size:.73rem}.latest-summary{background:#f7f9fc;border:1px solid #edf1f6;border-radius:11px;padding:1rem}.latest-summary small{color:#8492a6;display:block;font-size:.68rem;font-weight:600;text-transform:uppercase}.latest-summary strong{color:#173b74;display:block;font-size:1.05rem;margin-top:.2rem}.revision-card{border:1px solid #e7ecf3;border-radius:11px;margin-bottom:.8rem;overflow:hidden}.revision-card:last-child{margin-bottom:0}.revision-head{align-items:center;background:#f8fafc;border-bottom:1px solid #edf1f6;display:flex;flex-wrap:wrap;gap:.7rem;justify-content:space-between;padding:.75rem .9rem}.revision-tag{background:#eaf1ff;border-radius:12px;color:#2f6fed;font-size:.68rem;font-weight:700;padding:.25rem .55rem}.revision-category{color:#334155;font-size:.82rem;font-weight:700}.revision-date{color:#8492a6;font-size:.68rem}.revision-body{padding:.9rem}.money-grid{display:grid;gap:.7rem;grid-template-columns:1fr 1fr;margin-bottom:.8rem}.money-box{background:#f8fafc;border-radius:8px;padding:.65rem}.money-box small{color:#8492a6;display:block;font-size:.66rem;text-transform:uppercase}.money-box strong{color:#173b74;font-size:.9rem}.revision-text{color:#64748b;font-size:.75rem;line-height:1.5}.revision-text strong{color:#42526b}.feedback-item{border-left:3px solid #2f6fed;padding:0 0 1rem 1rem}.feedback-item:last-child{padding-bottom:0}.feedback-title{color:#334155;font-size:.82rem;font-weight:700}.feedback-meta{color:#8492a6;font-size:.68rem}.feedback-copy{background:#f8fafc;border-radius:8px;color:#64748b;font-size:.75rem;margin-top:.45rem;padding:.65rem}.empty-state{color:#8492a6;padding:2rem 1rem;text-align:center}.empty-state i{display:block;font-size:2rem;margin-bottom:.4rem}.alert{border-radius:10px}
    .assessment-back{gap:0}.assessment-back>i{margin-right:.4rem}.case-meta span{gap:0}.case-meta span>i{flex:0 0 auto;margin-right:.45rem}.revision-text .text-muted>i{margin-right:.3rem}.submission-panel strong{align-items:center;display:flex}.submission-panel strong>i{flex:0 0 auto;margin-right:.35rem}.submission-panel .submit-button i{margin-right:.35rem!important}
    @media(max-width:767px){.case-hero{padding:1.2rem}.case-hero h2{font-size:1.3rem}.case-status{margin-top:.8rem}.assessment-card .card-body{padding:1.1rem}.money-grid{grid-template-columns:1fr}.save-button,.submit-button{justify-content:center;width:100%}}
</style>
@endpush

@section('content')
@php
    $latest = $case->assistanceRequest?->revisions?->sortByDesc('revision_number')->first();
@endphp
<div class="assessment-page">
    <a href="{{ route('eclip_assessor.cases.index') }}" class="assessment-back"><i class="mdi mdi-arrow-left"></i> Back to assessment queue</a>
    <section class="case-hero mb-4" aria-labelledby="assessment-case-number"><div class="d-flex flex-column flex-md-row justify-content-between align-items-md-start position-relative" style="z-index:1"><div><div class="case-eyebrow mb-1">Assistance Assessment</div><h2 id="assessment-case-number" class="mb-3">{{ $case->case_number }}</h2><div class="case-meta"><span><i class="mdi mdi-account-key-outline"></i>{{ $case->formerRebel->classified_id }}</span><span><i class="mdi mdi-map-marker-outline"></i>{{ $case->formerRebel->municipality?->name ?? 'Not assigned' }}</span><span><i class="mdi mdi-file-document-edit-outline"></i>{{ $case->assistanceRequest?->revisions?->count() ?? 0 }} {{ Str::plural('revision', $case->assistanceRequest?->revisions?->count() ?? 0) }}</span></div></div><span class="case-status"><i class="mdi mdi-progress-check mr-1"></i>{{ $case->status->label() }}</span></div></section>

    <div class="row">
        <div class="col-xl-8">
            @can('assessAssistance', $case)
                <section class="card assessment-card mb-4" aria-labelledby="assessment-form-title"><div class="card-body">
                    <div class="d-flex align-items-center mb-4"><div class="section-icon mr-3"><i class="mdi mdi-clipboard-text-outline"></i></div><div><h3 id="assessment-form-title" class="section-title">{{ $latest ? 'Create New Assessment Revision' : 'Create Assessment' }}</h3><p class="section-subtitle">Record the requested assistance and the amount supported by the assessment.</p></div></div>
                    @if($categories->isEmpty())
                        <div class="alert alert-warning mb-0"><i class="mdi mdi-alert-outline mr-1"></i>The Katuparan Center has not configured official assistance categories.</div>
                    @else
                        <form method="POST" action="{{ route('eclip_assessor.assessments.store', $case) }}" data-assessment-form>@csrf
                            <div class="row">
                                <div class="form-group col-lg-6"><label for="category_id" class="field-label">Assistance Category</label><select id="category_id" name="category_id" class="form-control @error('category_id') is-invalid @enderror" required><option value="">Select category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id', $latest?->category_id) == $category->id)>{{ $category->name }}</option>@endforeach</select>@error('category_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                                <div class="form-group col-md-6 col-lg-3"><label for="requested_amount" class="field-label">Requested Amount</label><div class="currency-input"><span class="currency-symbol" aria-hidden="true">₱</span><input id="requested_amount" type="number" name="requested_amount" value="{{ old('requested_amount', $latest?->requested_amount) }}" min="0.01" max="9999999999999.99" step="0.01" class="form-control @error('requested_amount') is-invalid @enderror" required></div>@error('requested_amount')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
                                <div class="form-group col-md-6 col-lg-3"><label for="assessed_amount" class="field-label">Assessed Amount <span class="optional">(optional draft)</span></label><div class="currency-input"><span class="currency-symbol" aria-hidden="true">₱</span><input id="assessed_amount" type="number" name="assessed_amount" value="{{ old('assessed_amount', $latest?->assessed_amount) }}" min="0" max="9999999999999.99" step="0.01" class="form-control @error('assessed_amount') is-invalid @enderror"></div>@error('assessed_amount')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
                            </div>
                            <div class="form-group"><label for="justification" class="field-label">Request Justification</label><textarea id="justification" name="justification" maxlength="10000" rows="4" class="form-control @error('justification') is-invalid @enderror" placeholder="Explain the beneficiary's need and basis for the requested assistance..." required>{{ old('justification', $latest?->justification) }}</textarea>@error('justification')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                            <div class="form-group"><label for="assessment_remarks" class="field-label">Assessment Remarks <span class="optional">(optional)</span></label><textarea id="assessment_remarks" name="assessment_remarks" maxlength="10000" rows="3" class="form-control @error('assessment_remarks') is-invalid @enderror" placeholder="Add assessment findings or conditions...">{{ old('assessment_remarks', $latest?->assessment_remarks) }}</textarea>@error('assessment_remarks')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                            @error('status')<div class="alert alert-danger py-2" role="alert">{{ $message }}</div>@enderror
                            <div class="d-flex flex-column flex-sm-row align-items-sm-center justify-content-between"><small class="text-muted mb-2 mb-sm-0"><i class="mdi mdi-history mr-1"></i>Saving creates an immutable new revision.</small><button class="btn btn-primary save-button" data-submit-button><i class="mdi mdi-content-save-outline mr-1"></i>Save Revision</button></div>
                        </form>
                    @endif

                    @if($latest?->assessed_amount !== null)
                        <div class="submission-panel mt-4"><div class="d-flex flex-column flex-md-row align-items-md-center justify-content-between"><div class="mb-3 mb-md-0"><strong><i class="mdi mdi-check-circle-outline mr-1"></i>Assessment ready for submission</strong><span>The latest revision includes an assessed amount and can proceed to DILG review.</span></div><form method="POST" action="{{ route('eclip_assessor.assessments.submit', $case) }}" data-submit-review-form>@csrf<button class="btn btn-success submit-button" data-submit-button><i class="mdi mdi-send"></i>Submit for DILG Review</button></form></div></div>
                    @endif
                    @error('assessment')<div class="alert alert-danger mt-3 mb-0" role="alert">{{ $message }}</div>@enderror
                </div></section>
            @endcan

            <section class="card assessment-card mb-4" aria-labelledby="revision-title"><div class="card-body">
                <div class="d-flex align-items-center mb-4"><div class="section-icon mr-3"><i class="mdi mdi-history"></i></div><div><h3 id="revision-title" class="section-title">Revision History</h3><p class="section-subtitle">Complete assessment trail with amounts, justification, and assessor.</p></div></div>
                @forelse($case->assistanceRequest?->revisions?->sortByDesc('revision_number') ?? [] as $revision)
                    <article class="revision-card"><div class="revision-head"><div class="d-flex align-items-center"><span class="revision-tag mr-2">Revision {{ $revision->revision_number }}</span><span class="revision-category">{{ $revision->category->name }}</span></div><span class="revision-date">{{ $revision->created_at->format('M d, Y · h:i A') }}</span></div><div class="revision-body"><div class="money-grid"><div class="money-box"><small>Requested</small><strong>₱{{ number_format((float)$revision->requested_amount,2) }}</strong></div><div class="money-box"><small>Assessed</small><strong>{{ $revision->assessed_amount !== null ? '₱'.number_format((float)$revision->assessed_amount,2) : 'Pending' }}</strong></div></div><div class="revision-text"><strong>Justification:</strong> {{ $revision->justification }}@if($revision->assessment_remarks)<div class="mt-2"><strong>Assessment remarks:</strong> {{ $revision->assessment_remarks }}</div>@endif<div class="mt-2 text-muted"><i class="mdi mdi-account-outline"></i> Recorded by {{ $revision->creator->name }}</div></div></div></article>
                @empty<div class="empty-state"><i class="mdi mdi-clock-outline"></i>No assessment revisions have been recorded.</div>@endforelse
            </div></section>
        </div>

        <div class="col-xl-4">
            @if($latest)
                <section class="card assessment-card mb-4"><div class="card-body"><h3 class="section-title mb-3">Latest Assessment</h3><div class="latest-summary mb-2"><small>Category</small><strong>{{ $latest->category->name }}</strong></div><div class="row"><div class="col-6 pr-1"><div class="latest-summary"><small>Requested</small><strong>₱{{ number_format((float)$latest->requested_amount,2) }}</strong></div></div><div class="col-6 pl-1"><div class="latest-summary"><small>Assessed</small><strong>{{ $latest->assessed_amount !== null ? '₱'.number_format((float)$latest->assessed_amount,2) : 'Pending' }}</strong></div></div></div></div></section>
            @endif
            @if($case->dilgReviews->isNotEmpty())
                <section class="card assessment-card mb-4" aria-labelledby="feedback-title"><div class="card-body"><div class="d-flex align-items-center mb-4"><div class="section-icon mr-3"><i class="mdi mdi-message-text-outline"></i></div><div><h3 id="feedback-title" class="section-title">DILG Feedback</h3><p class="section-subtitle">Review decisions and requested changes.</p></div></div>@foreach($case->dilgReviews->sortByDesc('reviewed_at') as $review)<article class="feedback-item"><div class="feedback-title">{{ str($review->decision)->replace('_',' ')->title() }} · Revision {{ $review->revision->revision_number }}</div><div class="feedback-meta">{{ $review->reviewed_at->format('M d, Y · h:i A') }} @if($review->reviewer) · {{ $review->reviewer->name }} @endif</div><div class="feedback-copy">{{ $review->feedback ?: 'No feedback provided.' }}</div></article>@endforeach</div></section>
            @endif
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
document.querySelectorAll('[data-assessment-form], [data-submit-review-form]').forEach(function(form){form.addEventListener('submit',function(){var button=form.querySelector('[data-submit-button]');button.disabled=true;button.innerHTML='<i class="mdi mdi-loading mdi-spin mr-1"></i>Processing...';});});
</script>
@endpush
