<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="robots" content="noindex,nofollow,noarchive"><title>JAPIC Certification Draft</title>
<style>
@page{size:A4 portrait;margin:0}*{box-sizing:border-box}body{margin:0;background:#e9ecef;color:#111;font-family:Arial,Helvetica,sans-serif}.toolbar{width:210mm;margin:12px auto;text-align:right}.toolbar a,.toolbar button{padding:8px 12px;margin-left:6px}.sheet{position:relative;width:210mm;min-height:297mm;margin:0 auto 16px;background:#fff;padding:17mm 19mm 15mm;font-size:11pt;line-height:1.42}.draft-mark{position:absolute;top:48%;left:18%;transform:rotate(-31deg);font-size:38pt;font-weight:700;color:rgba(150,0,0,.12);letter-spacing:3px;white-space:nowrap}.header{display:grid;grid-template-columns:1fr auto 1fr;align-items:start;text-align:center}.emblem{width:22mm;height:22mm;border:1px dashed #777;font-size:7pt;color:#666;display:flex;align-items:center;justify-content:center;padding:2mm}.committee{font-weight:700;font-size:12pt;padding-top:2mm}.headquarters{display:grid;grid-template-columns:1fr 1fr;gap:18mm;text-align:center;font-size:9.5pt;margin-top:2mm}.title{text-align:center;font-weight:700;text-decoration:underline;letter-spacing:7px;font-size:15pt;margin:8mm 0 5mm}.meta{line-height:1.65}.photo{float:right;width:35mm;height:42mm;margin:0 0 4mm 7mm;border:1px solid #111;display:flex;align-items:center;justify-content:center;text-align:center;font-size:8pt;overflow:hidden}.photo img{width:100%;height:100%;object-fit:cover}.narrative{text-align:justify;text-indent:13mm;margin-top:6mm}.purpose{text-align:justify;text-indent:13mm;margin:5mm 9mm}.label{font-weight:700;margin-top:6mm}.signatories{display:grid;grid-template-columns:1fr 1fr;column-gap:18mm;text-align:center}.signatory{break-inside:avoid;padding-top:17mm}.signatory .name{font-weight:700;border-bottom:1px solid #111;padding-bottom:1mm;text-transform:uppercase}.signatory .position{font-size:9.5pt}.copies{font-size:8.5pt;margin-top:7mm}.copies strong{display:block}@media print{body{background:#fff}.toolbar{display:none}.sheet{margin:0;box-shadow:none}}
</style></head><body>
@php $source=$payload['source_snapshot'];$certificate=$payload['certificate'];$signatories=$payload['signatories'];$areas=collect($source['operating_areas'] ?? [])->when(filled($certificate['operating_area_supplement'] ?? null),fn($c)=>$c->push($certificate['operating_area_supplement']))->filter()->implode(', '); @endphp
@unless($printMode)<div class="toolbar"><a href="{{ route('japic.certifications.show',$processing) }}">Back</a><a href="{{ route('japic.certifications.print',$processing) }}">Print view</a><button type="button" onclick="window.print()">Print</button></div>@endunless
<main class="sheet"><div class="draft-mark">DRAFT — NOT FINAL</div>
<header><div class="header"><div class="emblem">Official emblem pending.</div><div class="committee">JOINT AFP-PNP<br>INTELLIGENCE COMMITTEE</div><div class="emblem">Official emblem pending.</div></div>
<div class="headquarters"><div><strong>GENERAL HEADQUARTERS<br>ARMED FORCES OF THE PHILIPPINES</strong><br>Camp General Emilio Aguinaldo<br>Quezon City</div><div><strong>NATIONAL HEADQUARTERS<br>PHILIPPINE NATIONAL POLICE</strong><br>Camp Brigadier General Rafael Crame<br>Quezon City</div></div><div class="title">CERTIFICATION</div></header>
<div class="photo">@if($photoDataUri)<img src="{{ $photoDataUri }}" alt="Authoritative subject photograph">@else Authoritative photograph unavailable @endif</div>
<div class="meta"><strong>Date Issued:</strong> {{ filled($certificate['date_issued'] ?? null) ? \Carbon\Carbon::parse($certificate['date_issued'])->format('d F Y') : '________________' }}<br><strong>Control Number:</strong> {{ $processing->control_number }}</div>
<p class="narrative"><strong>THIS IS TO CERTIFY</strong> that <strong>{{ $source['subject_name'] }}</strong> @if(filled($source['alias'] ?? null)) also known as <strong>{{ $source['alias'] }}</strong> @endif @if(filled($source['classification'] ?? null)) ({{ $source['classification'] }}) @endif, residing in {{ $source['residential_address'] ?? '________________' }}, is a former {{ $source['former_position'] ?? '________________' }} of {{ $source['former_organization'] ?? '________________' }} @if($areas), operating in {{ $areas }} @endif. {{ ucfirst($source['pronouns']['subject'] ?? 'they') }} started {{ $source['pronouns']['possessive'] ?? 'their' }} affiliation with the Communist Terrorist Group (CTG) in {{ $source['affiliation_period'] ?? '________________' }} and surrendered to {{ $certificate['surrendering_unit'] ?? '________________' }} on {{ filled($certificate['surrender_date'] ?? null) ? \Carbon\Carbon::parse($certificate['surrender_date'])->format('d F Y') : '________________' }} at {{ $certificate['surrender_location'] ?? '________________' }}.</p>
<p class="purpose">{{ $purpose }}</p>
<div class="label">PREPARED BY:</div><div class="signatories">@foreach(['provincial_afp','provincial_pnp'] as $key)<div class="signatory"><div class="name">{{ trim(($signatories[$key]['rank'] ?? '').' '.($signatories[$key]['name'] ?? '').' '.($signatories[$key]['suffix'] ?? '')) ?: ' ' }}</div><div class="position">{{ $positions[$key] }}</div></div>@endforeach</div>
<div class="label">ATTESTED BY:</div><div class="signatories">@foreach(['area_afp','area_pnp'] as $key)<div class="signatory"><div class="name">{{ trim(($signatories[$key]['rank'] ?? '').' '.($signatories[$key]['name'] ?? '').' '.($signatories[$key]['suffix'] ?? '')) ?: ' ' }}</div><div class="position">{{ $positions[$key] }}</div></div>@endforeach</div>
<div class="copies"><strong>Copy Furnished:</strong>Task Force Balik Loob (TFBL);<br>DILG Provincial/HUC/ICC Office;<br>E-CLIP and Amnesty Program Cluster of NTF-ELCAC.</div>
</main>@if($printMode)<script>window.addEventListener('load',()=>window.print())</script>@endif</body></html>
