@extends('layouts.skydash-v')
@section('title', '39th IB Dashboard')
@section('heading', '39th Infantry Battalion')

@push('styles')
<style>
    .ib-page{--navy:#172b4d;--border:#e7ecf3}.ib-hero{background:linear-gradient(125deg,#173b74,#2f6fed);border-radius:18px;box-shadow:0 12px 30px rgba(47,111,237,.18);color:#fff;overflow:hidden;padding:1.7rem;position:relative}.ib-hero::after{background:rgba(255,255,255,.08);border-radius:50%;content:'';height:210px;position:absolute;right:-55px;top:-105px;width:210px}.ib-eyebrow{font-size:.7rem;font-weight:700;letter-spacing:.11em;opacity:.76;text-transform:uppercase}.ib-hero h2{color:#fff;font-size:1.65rem;font-weight:700}.ib-hero p{font-size:.82rem;opacity:.86}.hero-actions{display:flex;flex-wrap:wrap;gap:.55rem;justify-content:flex-end;position:relative;z-index:1}.hero-action{align-items:center;background:rgba(255,255,255,.15);border:1px solid rgba(255,255,255,.28);border-radius:9px;color:#fff;display:inline-flex;font-size:.72rem;font-weight:600;gap:.4rem;padding:.55rem .75rem}.hero-action:hover{background:#fff;color:#245cc4;text-decoration:none}
    .summary-card,.classification-card,.chart-card{border:1px solid var(--border);border-radius:14px;box-shadow:0 4px 16px rgba(23,43,77,.045)}.summary-card .card-body{align-items:center;display:flex;gap:.85rem;padding:1.05rem}.summary-icon{align-items:center;background:var(--summary-bg);border-radius:10px;color:var(--summary-color);display:flex;flex:0 0 42px;font-size:1.15rem;height:42px;justify-content:center}.summary-card strong{color:var(--navy);display:block;font-size:1.35rem;line-height:1.1}.summary-card span{color:#718096;font-size:.68rem;font-weight:700;text-transform:uppercase}.summary-blue{--summary-bg:#eaf1ff;--summary-color:#2f6fed}.summary-green{--summary-bg:#e8f8f1;--summary-color:#20a779}.summary-purple{--summary-bg:#f2ebff;--summary-color:#805ad5}
    .section-title{color:var(--navy);font-size:1rem;font-weight:700;margin:0 0 .2rem}.section-subtitle{color:#8492a6;font-size:.75rem;margin:0}.classification-card{overflow:hidden;position:relative}.classification-card::before{background:var(--tone);content:'';height:4px;left:0;position:absolute;right:0;top:0}.classification-card .card-body{padding:1.15rem}.classification-head{align-items:center;display:flex;justify-content:space-between}.classification-icon{align-items:center;background:var(--tone-bg);border-radius:9px;color:var(--tone);display:flex;height:36px;justify-content:center;width:36px}.classification-card h3{color:var(--navy);font-size:1.45rem;font-weight:700;margin:.8rem 0 .15rem}.classification-card h4{color:#42526b;font-size:.78rem;font-weight:700;margin:0}.classification-card p{color:#8492a6;font-size:.68rem;margin:.2rem 0 0}.tone-red{--tone:#dc4c58;--tone-bg:#ffebed}.tone-orange{--tone:#e78328;--tone-bg:#fff0e2}.tone-yellow{--tone:#c79512;--tone-bg:#fff7d8}.tone-green{--tone:#20a779;--tone-bg:#e8f8f1}.chart-card .card-body{padding:1.35rem}.chart-box{height:340px;position:relative}.chart-select{border:1px solid #dfe5ee;border-radius:8px;color:#52616f;font-size:.75rem;padding:.45rem .7rem}.legend-note{align-items:flex-start;background:#f8fafc;border-radius:9px;color:#718096;display:flex;font-size:.7rem;gap:.5rem;padding:.7rem .8rem}
    @media(max-width:767px){.ib-hero{padding:1.2rem}.ib-hero h2{font-size:1.35rem}.hero-actions{justify-content:flex-start;margin-top:1rem}.chart-box{height:290px}}
</style>
@endpush

@section('content')
@php
    $classifications = [
        ['Konsolidado', $statusCounts['Konsolidado'] ?? 0, 'tone-red', 'fa-flag', 'Organized NPA Influenced Areas'],
        ['Rekonsilida', $statusCounts['Rekonsilida'] ?? 0, 'tone-orange', 'fa-exclamation-triangle', 'Less Influenced Areas'],
        ['Expansion', $statusCounts['Expansion'] ?? 0, 'tone-yellow', 'fa-expand', 'Potential Threat Areas'],
        ['Recovery', $statusCounts['Recovery'] ?? 0, 'tone-green', 'fa-check-circle', 'Cleared Areas'],
    ];
@endphp
<div class="ib-page">
    <section class="ib-hero mb-4"><div class="row align-items-center position-relative" style="z-index:1"><div class="col-lg-8"><div class="ib-eyebrow mb-1">Operational overview</div><h2 class="mb-2">39th Infantry Battalion Dashboard</h2><p class="mb-0">Authorized RCSP area classification and former-rebel monitoring overview.</p></div><div class="col-lg-4"><div class="hero-actions"><a href="{{ route('ib39.areas.index') }}" class="hero-action"><i class="fa fa-map-marker"></i>Manage Areas</a><a href="{{ route('ib39.map') }}" class="hero-action"><i class="fa fa-map"></i>Operational Map</a></div></div></div></section>

    <div class="row"><div class="col-md-4 mb-4"><div class="card summary-card summary-blue h-100"><div class="card-body"><div class="summary-icon"><i class="fa fa-map-o"></i></div><div><strong>{{ number_format($stats['mapped']) }}</strong><span>Mapped barangays</span></div></div></div></div><div class="col-md-4 mb-4"><div class="card summary-card summary-green h-100"><div class="card-body"><div class="summary-icon"><i class="fa fa-crosshairs"></i></div><div><strong>{{ number_format($stats['active_areas']) }}</strong><span>Areas with FR records</span></div></div></div></div><div class="col-md-4 mb-4"><div class="card summary-card summary-purple h-100"><div class="card-body"><div class="summary-icon"><i class="fa fa-users"></i></div><div><strong>{{ number_format($stats['total_frs']) }}</strong><span>Total former rebels</span></div></div></div></div></div>

    <div class="d-flex align-items-end justify-content-between mb-3"><div><h3 class="section-title">Area Classification</h3><p class="section-subtitle">Current barangay distribution based on recorded FR counts.</p></div></div>
    <div class="row mb-2">@foreach($classifications as [$title,$count,$tone,$icon,$description])<div class="col-sm-6 col-xl-3 mb-4"><div class="card classification-card {{ $tone }} h-100"><div class="card-body"><div class="classification-head"><h4>{{ $title }}</h4><div class="classification-icon"><i class="fa {{ $icon }}"></i></div></div><h3>{{ number_format($count) }}</h3><p>{{ $description }}</p></div></div></div>@endforeach</div>

    <section class="card chart-card mb-4" aria-labelledby="distribution-title"><div class="card-body"><div class="d-flex flex-wrap align-items-start justify-content-between mb-3"><div><h3 id="distribution-title" class="section-title">Operational Distribution</h3><p class="section-subtitle">Compare area classifications or recorded FR totals by municipality.</p></div><label class="sr-only" for="chartType">Chart data</label><select id="chartType" class="chart-select mt-2 mt-sm-0"><option value="status">Classification distribution</option><option value="municipality">FRs by municipality</option></select></div><div class="chart-box"><canvas id="barangayChart" aria-hidden="true"></canvas></div><div class="legend-note mt-3"><i class="fa fa-info-circle"></i><span>Figures are aggregate monitoring totals. Access to record-level location information remains restricted to the authorized operational map.</span></div></div></section>
</div>
<div id="ib39Data" data-status='@json($statusCounts)' data-muni-labels='@json($perMunicipality->pluck('municipality'))' data-muni-values='@json($perMunicipality->pluck('frs'))' hidden></div>
@endsection

@push('scripts')
<script>
(function(){var el=document.getElementById('ib39Data');var status=JSON.parse(el.dataset.status||'{}');var municipalityLabels=JSON.parse(el.dataset.muniLabels||'[]');var municipalityValues=JSON.parse(el.dataset.muniValues||'[]');var labels=['Konsolidado','Rekonsilida','Expansion','Recovery'];var colors=['#dc4c58','#e78328','#d4aa26','#20a779'];var chart;function render(type){if(chart)chart.destroy();var byStatus=type==='status';chart=new Chart(document.getElementById('barangayChart').getContext('2d'),{type:'bar',data:{labels:byStatus?labels:municipalityLabels,datasets:[{label:byStatus?'Barangays':'Former rebels',data:byStatus?labels.map(function(label){return status[label]||0;}):municipalityValues,backgroundColor:byStatus?colors:'#2f6fed',borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,legend:{display:false},scales:{yAxes:[{ticks:{beginAtZero:true,precision:0},gridLines:{color:'#edf1f7',drawBorder:false}}],xAxes:[{gridLines:{display:false}}]}}});}render('status');document.getElementById('chartType').addEventListener('change',function(event){render(event.target.value);});})();
</script>
@endpush
